Update upgrade-chromedriver
Update README.md

diff --git a/upgrade-chromedriver b/upgrade-chromedriver
--- a/upgrade-chromedriver
+++ b/upgrade-chromedriver
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-set -e
+set -ue
 
-TMPDIR="/tmp"
+DOWNLOAD_DIR="/tmp"
 DEFAULT_TARGET_DIR="$HOME/.local/bin"
 DRY=0
 DOWNLOAD_ONLY=0
@@ -10,17 +10,23 @@ TARGET_DIR=""
 CHROME_VERSION=""
 USE_APT=0
 LEAVE_ZIP_ON_FAILURE=0
+PLATFORM=linux64
+FORCE=0
 
 usage() {
-    echo "Usage: $0 [OPTIONS]"
+    echo "Usage: $(basename $0) [OPTIONS]"
     echo ""
     echo "Options:"
     echo "  --dry                     Only check if an update is needed, do not install"
     echo "  --download-only           Download the archive but do not install"
-    echo "  --leave-zip-on-failure    Do not delete ZIP if install fails"
-    echo "  --target-dir DIR          Where to install chromedriver"
-    echo "  --version VERSION         Use this Chrome version (implies --dry)"
+    echo "  --leave-zip-on-failure    Do not delete archive if install fails"
+    echo "  -t, --target-dir DIR      Where to install chromedriver"
+    echo "  -d, --download-dir DIR    Where to download archive"
+    echo "  -v, --version VERSION     Use this Chrome version (implies --dry). Can be specified without key"
     echo "  --apt                     Use version from apt (implies --dry)"
+    echo "  --platform PLATFORM       Specify platform (default = linux64, the key implies --download-only)"
+    echo "                            Variants: linux64, mac-arm64, mac-x64, win32, win64"
+    echo "  -f, --force               Always download"
     echo "  -h, --help                Show this help"
     exit 1
 }
@@ -29,6 +35,7 @@ while [ $# -gt 0 ]; do
     case "$1" in
         --dry)
             DRY=1
+            DOWNLOAD_ONLY=0
             ;;
         --download-only)
             DOWNLOAD_ONLY=1
@@ -36,14 +43,27 @@ while [ $# -gt 0 ]; do
         --leave-zip-on-failure)
             LEAVE_ZIP_ON_FAILURE=1
             ;;
-        --target-dir)
+        -t|--target-dir)
             shift
             TARGET_DIR="$1"
             ;;
-        --version)
+	-d|--download-dir)
+	    shift
+            DOWNLOAD_DIR="$1"
+	    ;;
+        -v|--version)
             shift
             CHROME_VERSION="$1"
             DRY=1
+            ;;
+	-f|--force)
+	    FORCE=1
+	    ;;
+	--platform)
+	    shift
+	    PLATFORM="$1"
+	    DOWNLOAD_ONLY=1
+	    FORCE=1
             ;;
         --apt)
             USE_APT=1
@@ -53,12 +73,23 @@ while [ $# -gt 0 ]; do
             usage
             ;;
         *)
-            echo "Unknown option: $1"
-            usage
+            CHROME_VERSION="$1"
+            DRY=1
             ;;
     esac
     shift
 done
+
+TOOLS_MISSING=0
+for tool in curl jq unzip; do
+    if ! command -v "$tool" >/dev/null 2>&1; then
+        echo "Error: Required tool '$tool' is not installed"
+        TOOLS_MISSING=1
+    fi
+done
+if [ "$TOOLS_MISSING" = 1 ]; then
+    exit 1
+fi
 
 # Determine Chrome version
 if [ "$USE_APT" = 1 ]; then
@@ -79,7 +110,7 @@ fi
 echo "Chrome version = $CHROME_VERSION ($version_source)"
 
 # Check existing chromedriver
-if which chromedriver >/dev/null 2>&1; then
+if [ "$FORCE" != 1 ] && command -v chromedriver >/dev/null 2>&1; then
     INSTALLED_VERSION=$(chromedriver --version | cut -d ' ' -f 2)
     if [ "$CHROME_VERSION" = "$INSTALLED_VERSION" ]; then
         echo "Chromedriver $INSTALLED_VERSION already installed"
@@ -96,7 +127,7 @@ fi
 # Get download URL
 API="https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json"
 URL=$(curl -s "$API" |
-    jq -r --arg PLATFORM "linux64" --arg VERSION "$CHROME_VERSION" \
+    jq -r --arg PLATFORM "$PLATFORM" --arg VERSION "$CHROME_VERSION" \
         '.versions[] | select(.version==$VERSION).downloads.chromedriver[] | select(.platform==$PLATFORM).url')
 
 if [ -z "$URL" ]; then
@@ -108,10 +139,13 @@ echo "Download URL: $URL"
 
 if [ "$DRY" = 1 ]; then
     echo "Found downloadable chromedriver $CHROME_VERSION"
-    exit 0
+    if [ "$DOWNLOAD_ONLY" != 1 ]; then
+	exit 0
+    fi
 fi
 
-ZIP_PATH="${TMPDIR}/chromedriver.zip"
+# Download driver
+ZIP_PATH="${DOWNLOAD_DIR}/chromedriver-${PLATFORM}-${CHROME_VERSION}.zip"
 echo "Downloading chromedriver to $ZIP_PATH..."
 set +e
 curl -sL -o "$ZIP_PATH" "$URL"
@@ -129,30 +163,26 @@ if [ "$DOWNLOAD_ONLY" = 1 ]; then
     exit 0
 fi
 
+# Install driver
 if [ -z "$TARGET_DIR" ]; then
-    if which chromedriver >/dev/null 2>&1; then
-        TARGET_DIR=$(dirname "$(which chromedriver)")
+    if command -v chromedriver >/dev/null 2>&1; then
+        TARGET_DIR=$(dirname "$(command -v chromedriver)")
     else
         if [ -d "$DEFAULT_TARGET_DIR" ]; then
-        TARGET_DIR="$DEFAULT_TARGET_DIR"
+            TARGET_DIR="$DEFAULT_TARGET_DIR"
         else
-            TARGET_DIR="$TMPDIR"
+            TARGET_DIR="$DOWNLOAD_DIR"
         fi
         echo "No current chromedriver found. Installing to $TARGET_DIR"
     fi
 fi
 
-# Extract chromedriver
 echo "Installing chromedriver to $TARGET_DIR..."
-set +e
-unzip -d "$TARGET_DIR" -o -j "$ZIP_PATH" "*/chromedriver" >/dev/null
-unzip_status=$?
-set -e
 
-if [ $unzip_status -eq 0 ]; then
-    echo "Installed to $TARGET_DIR/chromedriver"
+if unzip -d "$TARGET_DIR" -o -j "$ZIP_PATH" "*/chromedriver" >/dev/null; then
     rm "$ZIP_PATH"
     ls -lh "$TARGET_DIR/chromedriver"
+    echo "chromedriver $CHROME_VERSION installed to $TARGET_DIR/chromedriver"
 else
     echo "Failed to extract chromedriver"
     if [ "$LEAVE_ZIP_ON_FAILURE" = 1 ]; then
