Check if release for self-update is available

diff --git a/upgrade-chromedriver b/upgrade-chromedriver
--- a/upgrade-chromedriver
+++ b/upgrade-chromedriver
@@ -83,8 +83,13 @@ while [ $# -gt 0 ]; do
             RELEASE="${1:-}"
             QUERY_SUFFIX="${RELEASE:+tags/$RELEASE}"
             QUERY_SUFFIX="${QUERY_SUFFIX:-latest}"
-            curl -Ls \
-                "$(curl -s https://api.github.com/repos/a-zhenya/update-chromedriver/releases/$QUERY_SUFFIX | jq -r .tarball_url)" \
+            RELEASE_INFO="$(curl -s https://api.github.com/repos/a-zhenya/update-chromedriver/releases/$QUERY_SUFFIX)" 
+            if [ -z "$RELEASE_INFO" -o "$(echo $RELEASE_INFO | jq .status)" != null ]; then
+                echo "Failed to fetch release information: $QUERY_SUFFIX"
+                exit 1
+            fi
+            echo $RELEASE_INFO | jq -r '.tag_name + " " + .name + "\n" + .html_url + "\n" + .body'
+            curl -Ls "$(echo "$RELEASE_INFO" | jq -r .tarball_url)" \
                 | tar xvz --wildcards --overwrite --strip-components=1 --directory="$(dirname "$0")" "*/upgrade-chromedriver"
             chmod +x "$0"
             echo "Self-update complete"
